### ISSUE TITLE
[21] Make the bundles as small as possible

### ISSUE THREAD

**Issue by marcgear** [shiftcommerce/reference-site#9]
Bundle size is too big to be performant - several libraries are included multiple times.  We need this to not be this way

## Implementation detail
- [x] undo component-mapping.js

**Comment by owensmooth** [comment]
Currently reduced bundle size down as far as possible at the moment.
The next step to reduce the bundle size will be when we make pages/components extensible so that trendy doesn't pull in the full page and components from our packages and overwrite them.
